### ISSUE TITLE
DisallowedHost errors in the logs

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1485]
We got errors like this (different urls):

ERROR 2015-04-16 05:23:14,510 Internal Server Error: /robots.txt
Traceback (most recent call last):
  File "/var/akvo/rsr/versions/deploy-RSR_Deploy-74/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 204, in get_response
    response = middleware_method(request, response)
  File "/var/akvo/rsr/code/akvo/rsr/middleware.py", line 91, in process_response
    context = extra_context(request)
  File "/var/akvo/rsr/code/akvo/rsr/context_processors.py", line 18, in extra_context
    current_site = get_current_site(request)
  File "/var/akvo/rsr/versions/deploy-RSR_Deploy-74/venv/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 94, in get_current_site
    return real_get_current_site(request)
  File "/var/akvo/rsr/versions/deploy-RSR_Deploy-74/venv/local/lib/python2.7/site-packages/django/contrib/sites/shortcuts.py", line 18, in get_current_site
    return RequestSite(request)
  File "/var/akvo/rsr/versions/deploy-RSR_Deploy-74/venv/local/lib/python2.7/site-packages/django/contrib/sites/requests.py", line 16, in __init__
    self.domain = self.name = request.get_host()
  File "/var/akvo/rsr/versions/deploy-RSR_Deploy-74/venv/local/lib/python2.7/site-packages/django/http/request.py", line 90, in get_host
    raise DisallowedHost(msg)
DisallowedHost: Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.

**Comment by kardan** [comment]
I guess since we removed the Sites framework Django yanks the host name differently and now raises a DisallowedHost error.
