### ISSUE TITLE
Excel report issue

### ISSUE THREAD

**Issue by ifirmawan** [akvo/akvo-rsr#4557]
The downloading the project Excel report is leading to a 500 error:
![Excel-report-download-issue](https://user-images.githubusercontent.com/20871229/121656517-c3f85080-cac9-11eb-94f0-b39109132e06.gif)

**Comment by iperdomo** [comment]
````
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/akvo/rsr/code/akvo/rsr/decorators.py", line 50, in wrapper
    response = view(request, *args, **kwargs)
  File "/var/akvo/rsr/code/akvo/rsr/views/py_reports/project_results_indicators_excel_report.py", line 260, in render_report
    ws.set_cell_value(row, inner_col, period.get_disaggregation_of(category, type) or '')
  File "/var/akvo/rsr/code/akvo/rsr/views/py_reports/utils.py", line 454, in get_disaggregation_of
    if key not in self.approved_updates.disaggregations:
  File "/var/akvo/rsr/code/akvo/rsr/views/py_reports/utils.py", line 486, in disaggregations
    self._build()
  File "/var/akvo/rsr/code/akvo/rsr/views/py_reports/utils.py", line 529, in _build
    self._disaggregations[key]['value'] += d.value
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
````
