### ISSUE TITLE
Bug: Error during template rendering 

### ISSUE THREAD

**Issue by ronna** [akvo/akvo-rsr#4826]
### What were you doing?

Pulled the latest code from GitHub, run docker-compose build, then docker-compose up

### What should've happened?

I should have been able to view projects or login into my-rsr

### My environment

Running on a local machine
docker
Django Version: 3.2.10
Python Version: 3.8.1

### Additional context

Environment:

Request Method: GET
Request URL: http://157.230.228.89/en/project/134/

Django Version: 3.2.10
Python Version: 3.8.1
Installed Applications:
('nested_inline',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'akvo.codelists',
 'akvo.rsr',
 'sorl.thumbnail',
 'embed_video',
 'django_markup',
 'django_filters',
 'tastypie',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_framework_swagger',
 'bootstrap3',
 'rules',
 'django_crontab',
 'django_pgviews',
 'webpack_loader',
 'prettyjson',
 'lockdown',
 'request_token')
Installed Middleware:
('akvo.rsr.middleware.HostDispatchMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.http.ConditionalGetMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.admindocs.middleware.XViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'akvo.rsr.middleware.RequestTokenMiddleware',
 'akvo.rsr.middleware.ExceptionLoggingMiddleware',
 'akvo.rsr.middleware.RSRVersionHeaderMiddleware',
 'akvo.rsr.middleware.APIRedirectMiddleware',
 'akvo.rsr.middleware.RSRLockdownMiddleware')

Template error:
In template /var/akvo/rsr/code/akvo/templates/base.html, error at line 59
   expected string or bytes-like object
   49 :     {% endif %}
   50 :     {% if page_stylesheet %}&lt;link rel="stylesheet" href="{{MEDIA_URL}}{{page_stylesheet}}"&gt;{% endif %}
   51 : 
   52 :     &lt;style type="text/css"&gt;
   53 :         /** FIX for Bootstrap and Google Maps Info window styes problem **/
   54 :         img[src*="gstatic.com/"], img[src*="googleapis.com/"] {
   55 :         max-width: none;
   56 :         }
   57 :     &lt;/style&gt;
   58 : 
   59 :      {% render_bundle 'main' 'css' %} 
   60 : 
   61 :     {% block head %}{% endblock head %}
   62 : 
   63 :     {% block head_js %}{% endblock %}
   64 :   &lt;/head&gt;
   65 : 
   66 :   &lt;body&gt;
   67 :     {% piwik_tracking_code %}
   68 : 
   69 :     {% include 'navigation/header.html' %}

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/akvo/rsr/code/akvo/rsr/views/project.py", line 154, in main
    return render(request, template, context)
  File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.8/site-packages/webpack_loader/templatetags/webpack_loader.py", line 20, in render_bundle
    tags = utils.get_as_tags(
  File "/usr/local/lib/python3.8/site-packages/webpack_loader/utils.py", line 61, in get_as_tags
    bundle = _get_bundle(bundle_name, extension, config)
  File "/usr/local/lib/python3.8/site-packages/webpack_loader/utils.py", line 39, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/usr/local/lib/python3.8/site-packages/webpack_loader/loader.py", line 97, in get_bundle
    filtered_chunks = self.filter_chunks(chunks)
  File "/usr/local/lib/python3.8/site-packages/webpack_loader/loader.py", line 45, in filter_chunks
    ignore = any(regex.match(chunk)
  File "/usr/local/lib/python3.8/site-packages/webpack_loader/loader.py", line 45, in &lt;genexpr&gt;
    ignore = any(regex.match(chunk)

Exception Type: TypeError at /en/project/134/
Exception Value: expected string or bytes-like object

**Comment by MichaelAkvo** [comment]
Hi @ronna 

Sorry for the late response. For some reason I didn't get a notification...

Did you already have an old version of RSR running?
The error is probably from the new webpack loader. 

If you're still experiencing the error, could you try deleting the following files

 - akvo/rsr/front-end/static/webpack-stats.json
 - akvo/rsr/front-end/node_modules
 - akvo/rsr/front-end/static/rsr/dist/vendors.js

**Comment by ronna** [comment]
Hi @MichaelAkvo 



> Sorry for the late response. For some reason I didn't get a notification...
No worries. Thanks for having a look and responding to the issue.



> Did you already have an old version of RSR running?
Yes, I was running an old version of RSR, I am actually testing RSR locally and regularly pull code from the master branch and test.

I destroyed the local docker images and did run from scratch and the error disappeared.
