### ISSUE TITLE
Bug: Login fails in RSR training envs with timezone awareness activated

### ISSUE THREAD

**Issue by MichaelAkvo** [akvo/akvo-rsr#4981]
### What were you doing?

After navigating to https://rsr3.akvotest.org/my-rsr/ and logging in, one is stuck with a spinner.

![image](https://user-images.githubusercontent.com/91939214/171410433-9c572318-d219-4c1a-8b19-dedbb11637f2.png)

### What should've happened?

Login should've been successful and page should've shown a list of projects.

### Additional context

Backend logs

```
ERROR:root:Exception handling request for /rest/v1/me/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 233, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/usr/local/lib/python3.8/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/authentication.py", line 127, in authenticate
    if not user or not user.is_active:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 246, in inner
    self._setup()
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 382, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 177, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 65, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 238, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/cached_db.py", line 38, in load
    self._cache.set(self.cache_key, data, self.get_expiry_age(expiry=s.expire_date))
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 268, in get_expiry_age
    delta = expiry - modification
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**Comment by MichaelAkvo** [comment]
```
>>> settings.USE_TZ
True
```

**Comment by MichaelAkvo** [comment]
Our database tables are just super-old. The project started when `timestamp without time zone` was used for `DateTimeField` columns. A migration for this never came and [django's migration documentation](https://docs.djangoproject.com/en/3.2/topics/i18n/timezones/#postgresql) even indicates that no action is required.
If somebody else runs into this issue on postgres, just run `alter table django_session alter column expire_date TYPE TIMESTAMPTZ;` on your DB and you should be fine.
